### ISSUE TITLE
Lot of Error after Upgrading in EF Core 2

### ISSUE THREAD

**Issue by gawdenitish36** [DevExpress/EF-Core-Security#5]
I found build Error in some following Classes.
SecurityQueryCompiler,SecurityDatabaseProviderServices etc.

**Comment by AntonShabuninDx** [comment]
We are glad to hear that you are interested in this project. Though we are not actively involved in its development at the moment, we would appreciate it if you tell us more about your experience of applying this solution and about your business scenarios where our solution could help. Also, is the support for our security system for the EF Core important to you? Or you are fine to use XPO or common Entity Framework with DevExpress XAF instead?

**Comment by gawdenitish36** [comment]
I am already use XAF and i love it but you already know some Limitations of it. That's why i am working with Asp.net core for now. i want to implement XAF Security System in my Asp.net core Project.

**Comment by AntonShabuninDx** [comment]
Would you please clarify what limitation you mean? You can reply to: support@devexpress.com, or create a new ticket in the Support Center at: https://www.devexpress.com/ask. 
Currently we have no plans to update the EF-Core-Security project, but if you make this work, please share your results and the link to your repository fork with us. We would really appreciate it.

**Comment by gawdenitish36** [comment]
https://www.devexpress.com/Support/Center/Question/Details/T586896/ef-core-security-upgrade-problem
