### ISSUE TITLE
hello. are you planning to update it to .net core 2.0

### ISSUE THREAD

**Issue by aboyaniv** [DevExpress/EF-Core-Security#6]
Hello. 

Are you planning to update it to .net core 2.0 (and 2.1)?

**Comment by AntonShabuninDx** [comment]
Hello,

Currently we have no plans to update the EF-Core-Security project, but if you make this work, please share your results and the link to your repository fork with us. Thanks.

**Comment by dennis-garavsky** [comment]
I hope you will find the https://docs.microsoft.com/en-us/dotnet/core/migration/20-21 and related migration guidelines helpful.

By the way, am I correct that you already used the previous version in your project? If so, we would be grateful to learn more about your usage scenarios and general experience. Which competitive frameworks or technologies did you consider for the same task and what are your main choice criteria? This information will help us prioritize future work on this project.
